def compute_pca_maps(patch_features, n_components=3):
    raise NotImplementedError(
        "Use vit_pca_pipeline.py or cnn_pca_pipeline.py to generate saved PCA maps."
    )


def visualise_pca_map(pca_map, original_image=None, save_path=None):
    raise NotImplementedError("PCA overlays are generated by the PCA pipeline scripts.")
