def attention_rollout(attentions, head_fusion="mean"):
    raise NotImplementedError("The ViT analysis uses GMAR in vit_gmar_pipeline.py.")


def visualise_xai_map(xai_map, original_image=None, save_path=None):
    raise NotImplementedError("XAI overlays are generated by the GMAR and Grad-CAM pipelines.")
